
export const RETRIEVE_TOKEN = "RETRIEVE_TOKEN";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_DRIVER_REQUEST = "REGISTER_DRIVER_REQUEST";
export const REGISTER_DRIVER_SUCCESS = "REGISTER_DRIVER_SUCCESS";
export const REGISTER_DRIVER_FAIL = "REGISTER_DRIVER_FAIL";

export const LOAD_DRIVER_REQUEST = "LOAD_DRIVER_REQUEST";
export const LOAD_DRIVER_SUCCESS = "LOAD_DRIVER_SUCCESS";
export const LOAD_DRIVER_FAIL = "LOAD_DRIVER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_DRIVERS_REQUEST = "ALL_DRIVERS_REQUEST";
export const ALL_DRIVERS_SUCCESS = "ALL_DRIVERS_SUCCESS";
export const ALL_DRIVERS_FAIL = "ALL_DRIVERS_FAIL";

export const DRIVER_DETAILS_REQUEST = "DRIVER_DETAILS_REQUEST";
export const DRIVER_DETAILS_SUCCESS = "DRIVER_DETAILS_SUCCESS";
export const DRIVER_DETAILS_FAIL = "DRIVER_DETAILS_FAIL";

export const UPDATE_DRIVER_REQUEST = "UPDATE_DRIVER_REQUEST";
export const UPDATE_DRIVER_SUCCESS = "UPDATE_DRIVER_SUCCESS";
export const UPDATE_DRIVER_RESET = "UPDATE_DRIVER_RESET";
export const UPDATE_DRIVER_FAIL = "UPDATE_DRIVER_FAIL";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAIL = "DELETE_DRIVER_FAIL";
export const DELETE_DRIVER_RESET = "DELETE_DRIVER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
