export const LOAD_JOB_REQUEST = "LOAD_JOB_REQUEST";
export const LOAD_JOB_SUCCESS = "LOAD_JOB_SUCCESS";
export const LOAD_JOB_FAIL = "LOAD_JOB_FAIL";

export const LOAD_JOB_LOCATION_REQUEST = "LOAD_JOB_LOCATION_REQUEST";
export const LOAD_JOB_LOCATION_SUCCESS = "LOAD_JOB_LOCATION_SUCCESS";
export const  LOAD_JOB_LOCATION_FAIL = "LOAD_JOB_LOCATION_FAIL";

export const LOAD_ALL_JOBS_REQUEST = "LOAD_ALL_JOBS_REQUEST";
export const LOAD_ALL_JOBS_SUCCESS = "LOAD_ALL_JOBS_SUCCESS";
export const LOAD_ALL_JOBS_FAIL = "LOAD_ALL_JOBS_FAIL";

export const LOAD_ALL_JOBSDONE_REQUEST = "LOAD_ALL_JOBSDONE_REQUEST";
export const LOAD_ALL_JOBSDONE_SUCCESS = "LOAD_ALL_JOBSDONE_SUCCESS";
export const LOAD_ALL_JOBSDONE_FAIL = "LOAD_ALL_JOBSDONE_FAIL";