export const LOAD_CAB_REQUEST = "LOAD_CAB_REQUEST";
export const LOAD_CAB_SUCCESS = "LOAD_CAB_SUCCESS";
export const LOAD_CAB_FAIL = "LOAD_CAB_FAIL";

export const LOAD_CAB_LOCATION_REQUEST = "LOAD_CAB_LOCATION_REQUEST";
export const LOAD_CAB_LOCATION_SUCCESS = "LOAD_CAB_LOCATION_SUCCESS";
export const  LOAD_CAB_LOCATION_FAIL = "LOAD_CAB_LOCATION_FAIL";

export const LOAD_ALL_CABS_REQUEST = "LOAD_ALL_CABS_REQUEST";
export const LOAD_ALL_CABS_SUCCESS = "LOAD_ALL_CABS_SUCCESS";
export const LOAD_ALL_CABS_FAIL = "LOAD_ALL_CABS_FAIL";

